using RWMaintenance;
Service Service1;
Service1 = new Service(13, 342, RepairType.Urgent, "Олег", "Карпов", "ПЕтрович", 1234.4, "FWE", DateTime.Parse("April 2, 2023"));
Console.WriteLine(Service1.GetInfo());
CarDepot CarDepot1;
CarDepot1 = new CarDepot("TTT", new List<string>(){"работа1", "робта2", "работа3"}, 23);
Console.WriteLine(CarDepot1.GetInfo());
LocomotiveDepot LocomotiveDepot1;
LocomotiveDepot1 = new LocomotiveDepot("rrr", new List<string>(){"work1", "work2", "work3"}, LocoType.ElectroLoco);
Console.WriteLine(LocomotiveDepot1.GetInfo());